# Setup
title:        Adversarially Learned Inference
tagline:      Website for the Adversarially Learned Inference paper
baseurl:      ""

# About/contact
author:
  name:       Ishmael Belghazi
  url:        https://github.com/IshmaelBelghazi

#Others
markdown: kramdown
