# Setup
title:        Adversarially Learned Inference
tagline:      Vincent Dumoulin, Ishmael Belghazi, Ben Poole, Alex Lamb, Martin Arjovsky, Olivier Mastropietro and Aaron Courville
baseurl:      "/ALI"

# About/contact
author:
  name:       Ishmael Belghazi
  url:        https://github.com/IshmaelBelghazi

#Others
markdown: kramdown
